name: Deploy HTML Website

on:
  push:
    branches:
      - main

jobs:
  moin:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Copy project files to server
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        source: "./*"
        target: "/home/moin/site" 

    - name: SSH into server and build & restart container
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /home/moin/site
          docker stop mysite || true
          docker rm mysite || true
          docker build -t mysite .
          docker run -d -p 80:80 --name mysite mysite
